steps:
  # Build the container image for the specified agent
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_IMAGE_PATH}', 
        '-f',
        '${_AGENT_NAME}/Dockerfile', # Dynamically point to the correct Dockerfile
        '.', 
      ]

images:
  - '${_IMAGE_PATH}'